// <auto-generated />
using System;
using APIResevaDeLaboratorio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIResevaDeLaboratorio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.LaboratorioProfessor", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("LaboratorioId", "ProfessorId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("LaboratorioProfessores");
                });

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.LaboratorioTurma", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("LaboratorioId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("LaboratorioTurmas");
                });

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.ProfessorTurma", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("ProfessorTurmas");
                });

            modelBuilder.Entity("Laboratorio", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LaboratorioId"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LaboratorioId");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DuracaoEmMinutos")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ReservaDeLaboratorioContext.Models.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfessorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProfessorId");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("ReservaDeLaboratorioContext.Models.Turma", b =>
                {
                    b.Property<int>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TurmaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeAlunos")
                        .HasColumnType("int");

                    b.HasKey("TurmaId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.LaboratorioProfessor", b =>
                {
                    b.HasOne("Laboratorio", "Laboratorio")
                        .WithMany("LaboratorioProfessores")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaDeLaboratorioContext.Models.Professor", "Professor")
                        .WithMany("LaboratorioProfessores")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.LaboratorioTurma", b =>
                {
                    b.HasOne("Laboratorio", "Laboratorio")
                        .WithMany("LaboratorioTurmas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaDeLaboratorioContext.Models.Turma", "Turma")
                        .WithMany("LaboratorioTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("APIResevaDeLaboratorio.Models.ProfessorTurma", b =>
                {
                    b.HasOne("ReservaDeLaboratorioContext.Models.Professor", "Professor")
                        .WithMany("ProfessorTurmas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaDeLaboratorioContext.Models.Turma", "Turma")
                        .WithMany("ProfessorTurmas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Reserva", b =>
                {
                    b.HasOne("Laboratorio", "Laboratorio")
                        .WithMany("Reservas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaDeLaboratorioContext.Models.Professor", "Professor")
                        .WithMany("Reservas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservaDeLaboratorioContext.Models.Turma", "Turma")
                        .WithMany("Reservas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Laboratorio", b =>
                {
                    b.Navigation("LaboratorioProfessores");

                    b.Navigation("LaboratorioTurmas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservaDeLaboratorioContext.Models.Professor", b =>
                {
                    b.Navigation("LaboratorioProfessores");

                    b.Navigation("ProfessorTurmas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservaDeLaboratorioContext.Models.Turma", b =>
                {
                    b.Navigation("LaboratorioTurmas");

                    b.Navigation("ProfessorTurmas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
